### ISSUE TITLE
initialization of the module

### ISSUE THREAD

**Issue by sysadmin-info** [cljoly/gohugo-asciinema#8]
Hi,

Why not this way?

```
hugo mod init github_URL_to_the_project?
```

See this: https://gohugo.io/hugo-modules/use-modules/

**Comment by sysadmin-info** [comment]
Total nonsense question.

**Comment by cljoly** [comment]
No worries. I use a URL I own for the module so that I host the code outside of GitHub in the future if I want to, without breaking anything for users.
